services:
  resourcespace:
    image: davidloe/resourcespace:${RS_VERSION}
    restart: always
    depends_on:
      - db
    volumes:
      - resourcespace_filestore:/var/www/resourcespace/filestore
      - ./config.php:/var/www/resourcespace/include/config.php
    ports:
      - 80:80

  clip:
    image: davidloe/resourcespace-clip:${RS_VERSION}
    command: --dbuser $MARIADB_USER --dbpass $MARIADB_PASSWORD
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:10
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_data:
  resourcespace_filestore:
