services:
  resourcespace:
    build:
      context: .
      args:
        - RS_VERSION=10.6
    restart: always
    depends_on:
      - db
    volumes:
      - filestore:/var/www/html/filestore
      - ./config.php:/var/www/html/include/config.php
    ports:
      - 80:80

  db:
    image: mariadb:12
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root-pw
      - MARIADB_USER=resourcespace_rw
      - MARIADB_PASSWORD=resourcespace_rw-pw
      - MARIADB_DATABASE=resourcespace

volumes:
  db_data:
  filestore:
